apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/busybox:1.27.2
    args:
    - /bin/sh
    - -c
    # Simulamos: 10s para crear el archivo (arranque), 
    # luego el archivo vive para siempre (app sana).
    - sleep 10; touch /tmp/healthy; sleep 600
    
    # 1. Startup: Esperará hasta 30 segundos (3 * 10s) a que el archivo aparezca.
    startupProbe:
      exec:
        command: [ "echo", "start" ]
      initialDelaySeconds: 60
      failureThreshold: 3
      periodSeconds: 10

    # 2. Liveness: SOLO empezará a preguntar DESPUÉS de que Startup pase a éxito.
    livenessProbe:
      exec:
        command: [ "echo", "live" ]
      periodSeconds: 10

    # 3. Readiness: Igual que liveness, espera al Startup.
    readinessProbe:
      exec:
        command: [ "echo", "read" ]
      periodSeconds: 5
