apiVersion: v1
kind: Pod
metadata:
  name: slow-start-app 
spec:
  containers:
  - name: etcd
    image: nginx 
    ports:
    - name: liveness-port
      containerPort: 80
    startupProbe:
      httpGet:
        path: /
        port: liveness-port
      failureThreshold: 90
      periodSeconds: 5

    livenessProbe:
      httpGet:
        path: /22
        port: liveness-port
      periodSeconds: 10
