apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  user: YWRtaW4=
  password: U3VwZXJTZWNyZXQxMjM=
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    # --- PYTHON APPLICATION ---
    - name: python-app
      image: python:3.11-slim
      command: ["/bin/sh", "-c"]
      args:
        - |
          # Install netcat for the readiness check
          apt-get update && apt-get install -y netcat-openbsd
          echo "App starting... 20s delay initiated"
          sleep 20
          python3 -m http.server 8080
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
      ports:
        - containerPort: 8080

      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - nc -z localhost 5432
        initialDelaySeconds: 5
        periodSeconds: 2
        successThreshold: 1
        failureThreshold: 3

    # --- POSTGRES DATABASE (Sidecar) ---
    - name: postgres-db
      image: postgres:15-alpine
      restartPolicy: Never
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
      ports:
        - containerPort: 5432
