apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    args: ["/bin/sh", "-c", "touch /tmp/healthy; sleep 600"]
    ports:
    - containerPort: 80
    livenessProbe:
      exec:
        command: ["cat", "/tmp/healthy"]
      initialDelaySeconds: 5
      periodSeconds: 5


  - name: nginx2
    image: nginx:1.14.2
    args: ["/bin/sh", "-c", "touch /tmp/healthy;  sleep 600"]
    livenessProbe:
      exec:
        command: ["cat", "/tmp/healthy"]
      initialDelaySeconds: 5
      periodSeconds: 5

  - name: nginx3
    image: nginx:1.14.2
    # Agregamos el comando para que el archivo exista en este contenedor también
    args: ["/bin/sh", "-c", "touch /tmp/healthy;  sleep 600"]
    ports:
    - containerPort: 8080
    livenessProbe:
      exec:
        command: ["cat", "/tmp/healthy"]
      initialDelaySeconds: 5
      periodSeconds: 5
