apiVersion: v1
kind: Pod
metadata:
  name: exit-error-pod
  labels:
    test: failure
spec:
  containers:
  - name: error-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["echo 'Iniciando y fallando...'; sleep 2; exit 1"]
  # OnFailure hará que Kubernetes intente reiniciarlo al detectar el código 1
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: exit-sucess-pod
  labels:
    test: failure
spec:
  containers:
  - name: error-container
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["echo...; sleep 2; exit 0"]
  # OnFailure hará que Kubernetes intente reiniciarlo al detectar el código 1
  restartPolicy: OnFailure
