apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: web
    env: prod
    tier: frontend
  annotations:
    image-version: "2"
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: web
    env: dev
    tier: frontend
  annotations:
    image-version: "1"
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    app: api
    env: dev
    tier: backend
  annotations:
    image-version: "1"
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    app: app
    env: cache
    tier: backend
  annotations:
    image-version: "2"
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod5
  labels:
    app: web
    env: cache
    tier: frontend
  annotations:
    image-version: "1"
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
