apiVersion: v1
kind: Pod
metadata:
  labels:
    run: never-restart
  name: never-restart
spec:
  containers:
  - image: nginx:1.21
    name: never-restart
  dnsPolicy: ClusterFirst
  restartPolicy: Never 
status: {}
