apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp-standalone
    app: webapp
    version: v1
  name: webapp-standalone

spec:
  containers:
  - env:
    - name: APP_NAME
      value: WebApp
    - name: ENVIRONMENT
      value: production
    image: nginx:1.21-alpine
    imagePullPolicy: IfNotPresent
    name: webapp
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
