apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  labels:
    app: web-test
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-web
spec:
  selector:
    app: web-test # Esto conecta el servicio con el Pod
  ports:
    - protocol: TCP
      port: 80 # Puerto del servicio
      targetPort: 80 # Puerto del contenedor
