apiVersion: v1
kind: Pod
metadata:
  labels:
    run: excess-node
  name: excess-node
spec:
  containers:
  - image: nginx
    name: excess-node
    resources:
      requests:
        cpu: 1000m 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
