apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tolerate
  name: tolerate
spec:
  containers:
  - image: nginx
    name: tolerate
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"
