apiVersion: v1
kind: Pod
metadata:
  labels:
    run: memory-demo
  name: memory-demo
spec:
  containers:
  - image: nginx:1.21
    name: memory-demo
    command: ["sh", "-c", "x='a'; i=0; while [ $i -lt 25 ]; do x=$x$x;sleep 1; i=$((i+1)); echo 'Iteracion: $i'; done; sleep 600"]    
    resources:
      requests:
        memory: "240Mi"
      limits:
        memory: "520Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
