apiVersion: v1
data:
  API_1: MjEwMzEwMjAxMw==
  API_2: MTIzMDEyMDMwMQ==
  API_3: MTIwMzAxMzAxMg==
kind: Secret
metadata:
  name: api-keys
---
apiVersion: v1
data:
  DB_HOST: YXBpLmFwaS5hcGk=
  DB_PA: bm9yZWFs
  DB_USER: RmVsaXBl
kind: Secret
metadata:
  name: db-creds
---
apiVersion: v1
data:
  api: "true"
  test: "true"
kind: ConfigMap
metadata:
  name: feature-flags
---
apiVersion: v1
data:
  cache: "20"
  host: 192.10.0.1
  timeout: "20"
kind: ConfigMap
metadata:
  name: app-config
---
apiVersion: v1
kind: Pod
metadata:
  name: multi-files
spec:
  containers:
    - name: test-container
      image: nginx 
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: db_file
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: DB_HOST 
        - name: keys_file
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: API_1
        - name: feature_file
          valueFrom:
            configMapKeyRef:
              name: feature-flags
              key: test
        - name: config_file
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: cache
  restartPolicy: Never

