apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .secret-file: dmFsdWUtMg0KDQo=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        defaultMode: 0400
        secretName: secure-data 
        
  containers:
    - name: dotfile-test-container
      image: nginx
      command: ["sh", "-c"]
      args:
      - |
        ls -lL /etc/secret-volume/api-keys && \
        echo "Simulando movimiento de archivo..."
        echo "dato_extra" >> /etc/secret-volume/api-keys 2>&1
        sleep 1000      
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
