apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
      memory: 200Mi
    defaultRequest: # this section defines default requests
      cpu: 400m 
      memory: 200Mi
    max: # max and min define the limit range
      cpu: 1000m
    min:
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: nginx 
---

apiVersion: v1
kind: Pod
metadata:
  name: frontend-blocker
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        cpu: 400m
      limits:
        cpu: 400m
