apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: api-service-account 
  namespace: practice
---
apiVersion: v1
kind: Pod
metadata:
  name: api-client
spec:
  containers:
  - name: nginx
    image: curlimages/curl:8.1.0
    command: ["/bin/sh", "-c"]
    args:
    - |
      echo -n "Resultado de acceso a la API: "
      curl -sk -o /dev/null -w "%{http_code}\n" \
      -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
      https://kubernetes.default.svc/api/v1/namespaces/practice/pods
      sleep 3600
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  serviceAccountName: api-service-account 
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: vault-token
          expirationSeconds: 7200
          audience: vault

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: practice
  name: pod-reader
rules:
- apiGroups: [""] # El grupo vacío "" es para recursos core como pods
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-service-binding
  namespace: practice
subjects:
- kind: ServiceAccount
  name: api-service-account # Verifica que este nombre sea igual al de tu Pod
  namespace: practice
roleRef:
  kind: Role
  name: pod-reader # Debe coincidir con el nombre del Role anterior
  apiGroup: rbac.authorization.k8s.io
